spring:
  rabbitmq:
   # 单机配置
    host: 192.168.2.11 # 因为是消费者只需要连接一个rabbitmq实例，消费者则需要配置 addresses 集群
    port: 5672
    username: mqz
    password: mqz
    # 集群配置
    # addresses: 192.168.2.9:5672,192.168.2.7:5672 #,192.168.2.11:5672 # 集群ip地址
    #虚拟主机地址
    virtual-host: /
    connection-timeout: 15000
    template:
      mandatory: true # 设置为 true 后消息没有成功交换器到被路由到合适队列情况下会被return（ ReturnCallback函数）监听，而不会自动删除
    #消费端配置
    listener:
      simple:
        #消费端
        concurrency: 5
        #最大消费端数
        max-concurrency: 10
        # 如果消费者这边报错，设置重新消费策略
        retry:
          initial-interval: 5000ms # 重试间隔
          enabled: true # 开启重新消费策略
          max-attempts: 3 # 最大重新消费次数，若超过了这个次数还是失败，那么需要生产者重新发送消息过来消费，可以参考保证消息可靠性的案例（生产者定时扫库，投递未消费成功的消息）
        #限流（海量数据，同时只能过来一条）
#        prefetch: 1
#      direct:
#        prefetch: 1 #限流（海量数据，同时只能过来一条）
#      direct:
#        acknowledge-mode: manual  #配置手动确认，和 RabbitConfig 配置一样



server:
  port: 1111



#mars-swagger-better配置
swagger:
  enabled: true
  info:
    title: better-rabbit-mq消费方在线接口文档
    description: 消费方在线接口文档
    url: http://localhost:1111/doc.html
    contact: https://github.com/DemoMeng
    version: 1.0.0


knife4j:
  # 开启增强配置
  enable: true
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    username: mqz
    password: mengqizhang
#  自定义主页和自定义footer需要knife4j-spring-boot-starter版本大于等于2.0.8，
#  并且2.0.6需要springboot为2.2.x
#  setting:
#    #自定义主页
#    enableHomeCustom: true
#    homeCustomLocation: classpath:resources/home/welcome.md
#
#    #自定义footer
#    enableFooter: true
#    enableFooterCustom: true
#    footerCustomContent: SuperNiuBI License 2.0 | Copyright  2019-[浙江大拿有限公司](https://gitee.com/DemoMeng)

