version: "3.7"
services:
  rabbitmq-1:
    hostname: rabbitmq-host-1
    image: rabbitmq:3.8.9-management
    container_name: rabbitmq-1-container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /data/log:/var/log/rabbitmq/log
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=mqz
      - RABBITMQ_DEFAULT_PASS=mqz
    restart: on-failure
    privileged: true

