spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: mqz
    password: mqz
    #虚拟主机地址
    virtual-host: /
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
    connection-timeout: 15000
    publisher-returns: true
    template:
      mandatory: true
    #消费端配置
    listener:
        simple:
          #消费端
          concurrency: 5
          #最大消费端数
          max-concurrency: 10
          #自动签收auto  手动 manual
          acknowledge-mode: manual
          #限流（海量数据，同时只能过来一条）
          prefetch: 1

server:
  port: 1111
