services:
  rabbitmq1:
    image: rabbitmq:3.8.9-management
    container_name: rabbitmq1
    hostname: rabbit_host1
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    extra_hosts:
      - "rabbit_host1:192.168.2.9"
      - "rabbit_host2:192.168.2.11"
      - "rabbit_host3:192.168.2.7"
    volumes:
      - /root/mqz/rabbitmq/docker/lib:/var/lib/rabbitmq
      - /root/mqz/rabbitmq/docker/log:/var/log/rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=mqz
      - RABBITMQ_DEFAULT_PASS=mqz
      - RABBITMQ_NODENAME:rabbitmq1
      # RABBITMQ_ERLANG_COOKIE env variable support is deprecated and will be REMOVED in a future version. Use the $HOME/.erlang.cookie file or the --erlang-cookie switch instead.
      # - RABBITMQ_ERLANG_COOKIE=CURIOAPPLICATION




